config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  get 'search', to: 'search#search'
  get 'home', to: "homes#index"
  get 'pages/about', to: "pages#about"
  get 'pages/contact', to: "pages#contact"
  get 'publications', to: "publications#index"
  get 'series', to: "publications#series"
  get 'archive/:year', to: "publications#archive", as: "archive"

  get 'signin' => "sessions#new"
  resource :session

  resources :people, only: [:index, :show]
  resources :research, only: [:index]
  resources :research_themes, only: [:show]
  resources :research_projects, only: [:show]
  resources :news_items, only: [:show]
  resources :features, only: [:show]
  resources :documents, only: [:index]
  resources :publications, only: [:show]

  get 'admin', to: 'dashboard#index'
  namespace :admin do
    resources :research_themes
    resources :research_projects do
      member do
        patch :close
      end
    end
    resources :researchers do
      member do
        patch :hide
      end
    end
    resources :courses
    resources :news_items do
      member do
        patch :hide
      end
    end
    resources :publications do
      member do
        patch :hide
      end
      resources :documents
    end

    resources :features
    resources :research_groups

  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :require_signin
  before_filter :require_admin  

  private

  def require_admin
    unless current_user_admin?
      flash[:alert] = "Unauthorized access!"
      redirect_to home_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < AuthenticatedController
  before_filter :require_admin  

  private

  def require_admin
    unless current_user_admin?
      flash[:alert] = "Unauthorized access!"
      redirect_to home_path
    end
  end
end

app/views/dashboard/index.html.erb
<section class="dashboard">
    <h1 class="title">Dashboard</h1>
    <nav>
    <ul>
      <li><%= link_to "Research Themes", admin_research_themes_path %></li>
      <li><%= link_to "Research Projects", admin_research_projects_path %></li>
      <li><%= link_to "Researchers", admin_researchers_path %></li>
      <li><%= link_to "Courses", admin_courses_path %></li>
      <li><%= link_to "News Items", admin_news_items_path %></li>
      <li><%= link_to "Publications", admin_publications_path %></li>
      <li><%= link_to "In the picture", admin_features_path %></li>
      <li><%= link_to "Affiliated Research Groups", admin_research_groups_path %></li>
    </ul>
    </nav>
</section>