config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  get 'search', to: 'search#search'
  get 'home', to: "homes#index"
  get 'pages/about', to: "pages#about"
  get 'pages/contact', to: "pages#contact"
  get 'publications', to: "publications#index"
  get 'series', to: "publications#series"
  get 'archive/:year', to: "publications#archive", as: "archive"

  get 'signin' => "sessions#new"
  resource :session

  resources :people, only: [:index, :show]
  resources :research, only: [:index]
  resources :research_themes, only: [:show]
  resources :research_projects, only: [:show]
  resources :news_items, only: [:show]
  resources :features, only: [:show]
  resources :documents, only: [:index]
  resources :publications, only: [:show]

  get 'admin', to: 'dashboard#index'
  namespace :admin do
    resources :research_themes
    resources :research_projects do
      member do
        patch :close
      end
    end
    resources :researchers do
      member do
        patch :hide
      end
    end
    resources :courses
    resources :news_items do
      member do
        patch :hide
      end
    end
    resources :publications do
      member do
        patch :hide
      end
      resources :documents
    end

    resources :features
    resources :research_groups

  end

end

app/models/research_project.rb
class ResearchProject < ActiveRecord::Base
  include Closeable
  include Searchable

  scope :by_created_at, ->{ order(:created_at) }

  validates :title, :body, presence: true
  validates :image, format: { :with => /\.(png|gif|jpg|jpeg)\z/i },
                      allow_blank: true
  validate :image_size

  has_many :theme_projects, dependent: :destroy
  has_many :research_themes, through: :theme_projects

  has_many :project_researchers
  has_many :researchers, through: :project_researchers

  has_many :project_publications
  has_many :publications, through: :project_publications

  mount_uploader :image, ResearchProjectImageUploader
  
  private


  def image_size
    if image.size > 3.megabytes
      errors.add(:image, "should be less than 3MB")
    end
  end
end

# Delete the previous publication index in Elasticsearch
Publication.__elasticsearch__.client.indices.delete index: Publication.index_name rescue nil

# Create the new index with the new mapping
Publication.__elasticsearch__.client.indices.create \
  index: Publication.index_name,
  body: { settings: Publication.settings.to_hash, mappings: Publication.mappings.to_hash }

# Index all article records from the DB to Elasticsearch
Publication.import(force: true)

app/controllers/admin/research_projects_controller.rb
class Admin::ResearchProjectsController < DashboardController 
  def index
    @research_projects = ResearchProject.all.by_created_at
  end

  def show
    @research_project = ResearchProject.find(params[:id])
  end

  def new
    @research_project = ResearchProject.new
  end

  def edit
    @research_project = ResearchProject.find(params[:id])
  end

  def create
    @research_project = ResearchProject.create(research_project_params)
    if @research_project.save
      redirect_to admin_research_projects_path, notice: "you successfully added a new research project"
    else
      flash[:alert] = @research_project.errors.full_messages.join(' ') 
      render :new
    end
  end

  def update
    @research_project = ResearchProject.find(params[:id])
    if @research_project.update(research_project_params)
    redirect_to admin_research_projects_path, notice: "you successfully updated the research project"
    else
      flash[:alert] = @research_project.errors.full_messages.join(' ') 
      render :edit
    end
  end

  def destroy
    research_project = ResearchProject.find(params[:id])
    research_project.destroy
    redirect_to admin_research_projects_path, notice: "you successfully removed the research project"
  end

  def close
    @research_project = ResearchProject.find(params[:id])
    @research_project.toggle_active!
    render "close.js.erb"
  end

  
  private

  def research_project_params
    params.require(:research_project).permit(:title, :body, :image, :remove_image, :active, :research_theme_ids => [])
  end
end

app/controllers/research_projects_controller.rb
class ResearchProjectsController < ApplicationController
  def show
    @research_project = ResearchProject.find(params[:id])
  end
end

app/views/admin/research_projects/_form.html.erb
<%= form_for [:admin, @research_project], html: { id: "research-project-form", multipart: true }  do |f| %>
  <fieldset>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <% if @research_project.image.present? %>
      <%= image_tag @research_project.image.url %>
      <%= f.check_box :remove_image %>
      remove image
    <% end %>
    <%= f.label :image %>
    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
  </div>
  <div>
     <%= f.label "Research Themes" %>
     <%= f.collection_check_boxes :research_theme_ids, ResearchTheme.all, :id, :title do |b| %>
       <%= b.label() { b.check_box + b.text } %>
     <% end %>
  </div>
  <% if @research_project.new_record? %>
    <%= f.button "Add Research Project", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Adding Research Project ..." } %>
  <% else %>
    <%= f.button "Update Research Project", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Updating Research Project ..." } %>
  <% end %>
  <%= link_to 'Cancel', admin_research_projects_path %>
</fieldset>
<% end %>

<% content_for :javascript do %>
  <script>
    $(function() {
          $("#research-project-form").validate({
            debug: false,
            onfocusout: true,
            rules: {
              "research_project[title]": { required: true},
              "research_project[body]": { required: true}
            },
            messages: {
              "research_project[title]": { required: "Title is required!" },
              "research_project[body]": { required: "Body is required!"}
            },
            onfocusout: function (element) {
              this.element(element);
            },
            onkeyup: function (element, event) {
              this.element(element);
            },
            errorClass: 'error'
        });
      });
  </script>
<% end %>

app/views/admin/research_projects/close.js.erb
$link = $("#research_project_<%= @research_project.id %>"); 
$link.text("<%= toggle_active(@research_project) %>");
if ($link.text() == "Close") {
  $(".messages").empty().append("<p class='notice'>The research project is now active</p>");
}
  else {
    $(".messages").empty().append("<p class='notice'>The research project is now closed</p>");
}

app/views/admin/research_projects/edit.html.erb
<% breadcrumb :research_project, @research_project %>
<h1>Edit Research Project</h1>
<%= render "form" %>

app/views/admin/research_projects/index.html.erb
<% breadcrumb :research_projects %>

<h1>Research Projects</h1>
<%= button_to "Add Research Project", new_admin_research_project_path, method: "get" %>
<table class="table-borders">
  <tbody>
    <% if @research_projects.count != 0 %>
      <% @research_projects.each do |project| %>
        <tr>
          <td><%= link_to project.title, admin_research_project_path(project) %></td>
          <td><%= link_to "Edit", edit_admin_research_project_path(project) %>&nbsp;&nbsp;<%= link_to "Delete", admin_research_project_path(project), method: :delete, data: { confirm: "Are you sure?" } %>&nbsp;&nbsp;
            <%= link_to toggle_active(project), close_admin_research_project_path(project), method: :patch, remote: true, id: dom_id(project) %>
      </td>

      </tr>
      <% end %>
    <% else %>
      <p class="no-items">There are no research projects. Click 'Add Research Project' to create one.</p>     
    <% end %>
  </tbody>
</table>

app/views/admin/research_projects/new.html.erb
<% breadcrumb :research_project, nil %>
<h1>Add new research project</h1>
<%= render "form" %>

app/views/admin/research_projects/show.html.erb
<% breadcrumb :research_project, @research_project %>

<div class="content">
  <h1><%= @research_project.title %></h1>
  <div>
    <h3>Bodytext</h3>
    <%= @research_project.body %>
  </div>
  <section>
  <h3>Research Themes</h3>
  <ul>
    <% @research_project.research_themes.each do |theme| %>
      <li><%= link_to theme.title, admin_research_theme_path(theme) %></li>
    <% end %>
  </ul>
  </section>
  <section>
    <h3>Researchers</h3>
    <ul>
      <% @research_project.researchers.each do |researcher| %>
        <li><%= link_to researcher.fullname, admin_researcher_path(researcher) %></li>
      <% end %>
    </ul>
  </section>
  <section>
    <h3>Publications</strong></h3>
    <ul>
      <% @research_project.publications.each do |publication| %>
        <li><%= link_to publication.title, admin_publication_path(publication) %></li>
      <% end %>
    </ul>
  </section>
</div>
<%= image_tag @research_project.image.url %>