config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  get 'search', to: 'search#search'
  get 'home', to: "homes#index"
  get 'pages/about', to: "pages#about"
  get 'pages/contact', to: "pages#contact"
  get 'publications', to: "publications#index"
  get 'series', to: "publications#series"
  get 'archive/:year', to: "publications#archive", as: "archive"

  get 'signin' => "sessions#new"
  resource :session

  resources :people, only: [:index, :show]
  resources :research, only: [:index]
  resources :research_themes, only: [:show]
  resources :research_projects, only: [:show]
  resources :news_items, only: [:show]
  resources :features, only: [:show]
  resources :documents, only: [:index]
  resources :publications, only: [:show]

  get 'admin', to: 'dashboard#index'
  namespace :admin do
    resources :research_themes
    resources :research_projects do
      member do
        patch :close
      end
    end
    resources :researchers do
      member do
        patch :hide
      end
    end
    resources :courses
    resources :news_items do
      member do
        patch :hide
      end
    end
    resources :publications do
      member do
        patch :hide
      end
      resources :documents
    end

    resources :features
    resources :research_groups

  end

end

app/models/researcher.rb
class Researcher < ActiveRecord::Base
  include Hideable

  scope :active, ->{ where(active: true).order(:last_name) }
  scope :not_active, ->{ where(active: false).order(:last_name) }
  scope :by_last_name, ->{ order(:last_name) }

  validates :first_name, :last_name, presence: true
  validates :last_name, :uniqueness => { :scope => :first_name }
  validates :bio, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness: { case_sensitive: false }

  validates_length_of :title, maximum: 30
  validates :image, format: { :with => /\.(png|gif|jpg|jpeg)\z/i },
                      allow_blank: true

  validate :image_size

  has_many :project_researchers
  has_many :research_projects, through: :project_researchers
  
  has_many :course_researchers
  has_many :courses, through: :course_researchers

  has_many :publication_researchers
  has_many :publications, through: :publication_researchers

  mount_uploader :image, ResearcherImageUploader

  def fullname
  "#{first_name} #{last_name}"
  end

  private

  def image_size
    if image.size > 3.megabytes
      errors.add(:image, "should be less than 3MB")
    end
  end
  

end

app/controllers/admin/researchers_controller.rb
class Admin::ResearchersController < DashboardController
  def index
    @researchers = Researcher.all.by_last_name
  end

  def show
    @researcher = Researcher.find(params[:id])
  end

  def new
    @researcher = Researcher.new
  end

  def edit
    @researcher = Researcher.find(params[:id])
  end

  def create
    @researcher = Researcher.create(researcher_params)
    if @researcher.save
      redirect_to admin_researchers_path, notice: "You successfully added a new researcher"
    else
      flash[:alert] = @researcher.errors.full_messages.join(' ') 
      render :new
    end
  end

  def update
    @researcher = Researcher.find(params[:id])
    if @researcher.update(researcher_params)
      redirect_to admin_researchers_path, notice: "you successfully updated the researcher #{@researcher.fullname}"
    else
      flash[:alert] = @researcher.errors.full_messages.join(' ')
      render :edit
    end
  end

  def destroy
    researcher = Researcher.find(params[:id])
    researcher.destroy
    redirect_to admin_researchers_path, notice: "You successfully removed the researcher"
  end

  def hide
    @researcher = Researcher.find(params[:id])
    @researcher.toggle_visibility!
    render "hide.js.erb"
  end

  private

  def researcher_params
    params.require(:researcher).permit(:active, :first_name, :last_name, :bio, :phone, :email, :address, :image, :remove_image, :title, :visible, :bibliography, :research_project_ids => [], :course_ids => [])
  end
end

app/views/admin/researchers/_form.html.erb
<%= form_for [:admin, @researcher], html: { id: "researcher-form", multipart: true } do |f| %>
  <fieldset>
  <div>
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :bio %>
    <%= f.text_area :bio, size: "20x10" %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "phone" %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_area :address, size: "20x3" %>
  </div>
  <div>
    <% if @researcher.image.present? %>
      <%= image_tag @researcher.image.url(:thumb) %>
      <%= f.check_box :remove_image %>
      remove image
    <% end %>
    <%= f.label :image %>
    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
  </div>
  <div>
    <%= f.label :bibliography %>
    <%= f.text_field :bibliography %>
  </div>
  <div>
     <%= f.label "Courses" %> 
     <%= f.collection_check_boxes :course_ids, Course.all, :id, :title do |b| %>
       <%= b.label() { b.check_box + b.text } %>
     <% end %>
  </div>
  <div>
     <%= f.label "Research Projects" %>
     <%= f.collection_check_boxes :research_project_ids, ResearchProject.all, :id, :title do |b| %>
       <%= b.label() { b.check_box + b.text } %>
     <% end %>
  </div>
  <% if @researcher.new_record? %>
    <%= f.button "Add Researcher", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Adding Researcher ..." } %>
  <% else %>
    <%= f.button "Update Researcher", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Updating Researcher ..." } %>
  <% end %>
  <%= link_to 'Cancel', admin_researchers_path, class: "cancel" %>
</fieldset>
<% end %>


<% content_for :javascript do %>
  <script>
    $(function() {
          $("#researcher-form").validate({
            debug: false,
            onfocusout: true,
            rules: {
              "researcher[title]": { maxlength: 30 },
              "researcher[first_name]": {required: true},
              "researcher[last_name]": { required: true},
              "researcher[email]": {required: true, email: true}
            },
            messages: {
              "researcher[title]": { maxlength: "Title can not be longer then 30 characters!" },
              "researcher[first_name]": { required: "First name is required!" },
              "researcher[last_name]": { required: "Last name is required!" },
              "researcher[email]": {
              required: "Email is required!",
              email: "Your email address must be in the format of name@domain.com"
              }
            },
            onfocusout: function (element) {
              this.element(element);
            },
            onkeyup: function (element, event) {
              this.element(element);
            },
            errorClass: 'error'
        });
        $('#researcher_bio').editable({
          inlineMode: false,

          // Set custom buttons with separator between them. Also include the name
          // of the buttons  defined in customButtons.
          buttons: ['bold', 'italic', 'insertUnorderedList', 'formatBlock', 'undo', 'redo', 'html'],
          blockTags: ['h3']
        })
      });
  </script>
<% end %>

app/views/admin/researchers/edit.html.erb
<% breadcrumb :researcher, @researcher %>
<h1>Edit Researcher</h1>
<%= render "form" %>

app/views/admin/researchers/hide.js.erb
$link = $("#researcher_<%= @researcher.id %>");
$link.text("<%= toggle_visibility(@researcher) %>");
if ($link.text() == "Hide") {
  $(".messages").empty().append("<p class='notice'>The researcher <%= @researcher.fullname %> is now visible</p>");
}
  else {
    $(".messages").empty().append("<p class='notice'>The researcher <%= @researcher.fullname %> is now hidden</p>");
}

app/views/admin/researchers/index.html.erb
<% breadcrumb :researchers %>
  <h1>Researchers</h1>
  <%= button_to 'Add Researcher', new_admin_researcher_path, method: "get" %>
  <table class="table-borders">
    <tbody>
      <% if @researchers.count != 0 %>
        <% @researchers.each do |researcher| %>
          <tr>
            <td><%= link_to researcher.fullname, admin_researcher_path(researcher) %></td>
            <td><%= link_to "Edit", edit_admin_researcher_path(researcher) %>&nbsp;&nbsp;
              <%= link_to "Delete", admin_researcher_path(researcher), method: :delete, data: { confirm: "Are you sure?" } %>&nbsp;&nbsp;
              <%= link_to toggle_visibility(researcher), hide_admin_researcher_path(researcher), method: :patch, remote: true, id: dom_id(researcher) %></td>
          </tr>
        <% end %>
      <% else %>
        <p class="no-items">There are no researchers. Click 'Add Researcher' to create one.</p>
      <% end %>
    </tbody>
  </table>

app/views/admin/researchers/new.html.erb
<% breadcrumb :researcher, nil %>
<h1>Add Researcher</h1>
<%= render "form" %>

app/views/admin/researchers/show.html.erb
<% breadcrumb :researcher, @researcher %>
  <div class="content">
  <h1><%= @researcher.fullname %></h1>
  <p><%= sanitize @researcher.bio, tags: %w(strong i p h3 ul li) %></p>
  <section>
  <h3>Contact</h3>
  <p><i class="fa fa-envelope"></i> <%= mail_to @researcher.email %><br />
  <i class="fa fa-phone"></i> <%= @researcher.phone %></p>
  </section>
  <section>
    <h3>Address</h3>
    <p><%= @researcher.address %></p>
  </section>
  <section>
    <h3>Bibliography</h3>
    <p><%= link_to @researcher.bibliography, @researcher.bibliography %></p>
  </section>
  <section>
    <h3>Courses</h3>
    <ul>
      <% @researcher.courses.each do |course| %>
        <li><%= link_to course.title, admin_course_path(course) %></li>
      <% end %>
    </ul>
  </section>
  <section>
    <h3>Research Projects</h3>
    <ul>
      <% @researcher.research_projects.each do |project| %>
        <li><%= link_to project.title, admin_research_project_path(project) %></li>
      <% end %>
    </ul>
  </section>
</div>
  <p><%= image_tag @researcher.image.url %>