config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  get 'search', to: 'search#search'
  get 'home', to: "homes#index"
  get 'pages/about', to: "pages#about"
  get 'pages/contact', to: "pages#contact"
  get 'publications', to: "publications#index"
  get 'series', to: "publications#series"
  get 'archive/:year', to: "publications#archive", as: "archive"

  get 'signin' => "sessions#new"
  resource :session

  resources :people, only: [:index, :show]
  resources :research, only: [:index]
  resources :research_themes, only: [:show]
  resources :research_projects, only: [:show]
  resources :news_items, only: [:show]
  resources :features, only: [:show]
  resources :documents, only: [:index]
  resources :publications, only: [:show]

  get 'admin', to: 'dashboard#index'
  namespace :admin do
    resources :research_themes
    resources :research_projects do
      member do
        patch :close
      end
    end
    resources :researchers do
      member do
        patch :hide
      end
    end
    resources :courses
    resources :news_items do
      member do
        patch :hide
      end
    end
    resources :publications do
      member do
        patch :hide
      end
      resources :documents
    end

    resources :features
    resources :research_groups

  end

end

app/views/shared/_footer.html.erb
<footer class="footer-2">
  <div class="footer-logo">
    <%= image_tag 'logo-ugent-small.png' %>
  </div>
    <ul>
      <li><a href="javascript:void(0)">&copy <%= Time.now.year %> UGent</a></li>
      <li><%= link_to "About", pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
    </ul>

    <div class="footer-secondary-links">
      <ul>
        <li><a href="http://www.ugent.be/en/disclaimer">Disclaimer</a></li>
      </ul>
    </div>
  </footer>

app/views/shared/_header.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href="javascript:void(0)" class="logo">
      <%= image_tag 'logo-posplus-72x61.png' %>
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"><%= link_to "POS+", home_path %></li>
        <li class="nav-link"><%= link_to "About", pages_about_path %></li>
        <li class="nav-link"><%= link_to "People", people_path %></li>
        <li class="nav-link"><%= link_to "Research", research_index_path %></li>
        <li class="nav-link"><%= link_to "Publications", publications_path %></li>
        <li class="nav-link"><%= link_to "Contact", pages_contact_path %></li>
      </ul>
    </div>
    <div class="navigation-tools">
      <div class="search-bar">
          <%= form_tag search_path, class: "search-and-submit", method: :get do %>
              <%= text_field_tag :q, params[:q], type: "search", placeholder: "Search publications, ..." %>
              <button type="submit", class: "search-button"><i class="fa fa-search"></i></button>
          <% end %>
      </div>
      <% if current_user_admin? %>
        <%= link_to "Admin", admin_path, class: "sign-up" %>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_messages.html.erb
<div class="signin">
<% if current_user %>
  Welcome <%= current_user.full_name %>
  <%= link_to 'Sign Out', session_path, method: :delete %>
<% end %>
</div>
<div class="messages">
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
</div>